bookms/urls.py
from django.contrib import admin
from django.urls import path
from .views import AddBookView, BookUpdateView, BookDeleteView,BookListView,BorrowBookView,ConfirmBookView,BorrowedBooksListView,ReturnBookView,ReturnBookDetailView
from . import views

app_name = 'bookms'

urlpatterns = [
    path('create/', AddBookView.as_view(), name='book-create'),
    path('list/', BookListView.as_view(), name='book_list'),
    path('update/<int:pk>/', BookUpdateView.as_view(), name='book_update'),
    path('delete/<int:pk>/', BookDeleteView.as_view(), name='book_delete'),
    path('<int:book_id>/borrow/',BorrowBookView.as_view(), name='book_borrow'), 
    path('borrow/<int:borrow_id>/confirm/',ConfirmBookView.as_view(), name='borrow_confirm'),
    path('borrowed_books/', BorrowedBooksListView.as_view(), name='borrowed_books_list'),
    path('return_book/<int:book_id>/', ReturnBookView.as_view(), name='return_book'),
    path('return_book/<int:borrow_id>/detail/', ReturnBookDetailView.as_view(), name='return_book_detail'),

]

managementsystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include("bookms.urls")),
]

bookms/models.py
from django.db import models
from django.contrib.auth.models import User

class BookModel(models.Model):
    name=models.CharField(max_length=100)
    price=models.IntegerField()
    version=models.CharField(max_length=100)
    author=models.CharField(max_length=100)
    publication_info=models.CharField(max_length=100, null=True)
    isbn=models.CharField(max_length=100, null=True)
    
    #presentation of model....
    def __str__(self) -> str:
        return self.name
    

class Borrow(models.Model):
    book = models.ForeignKey(BookModel, on_delete=models.CASCADE)
    borrowed_by = models.ForeignKey(User, on_delete=models.CASCADE)
    other_details = models.TextField(blank=True, null=True)  
    borrowed_at = models.DateTimeField(auto_now_add=True)
    returned = models.BooleanField(default=False) 
    returned_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Book {self.book.name} borrowed by {self.borrowed_by}"
    

bookms/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import CreateView,UpdateView,DeleteView,ListView,TemplateView,DetailView
from django.urls import reverse_lazy

from .models import BookModel,Borrow
from .Forms.book_status_form import BookStatusForm
from .Forms.form import BookForm
from .Forms.borrow_form import BorrowForm
from .table import BookTable
from django.contrib.auth.models import User
from django.urls import reverse





# Create your views here.

class AddBookView(CreateView):
    model=BookModel
    form_class = BookForm
    templates_name='bookmodel_form.html'
    success_url = reverse_lazy('bookms:book_list')


class NavbarView(CreateView):
    def get(self, request):
        return render(request, 'bookms/navbar.html')
    

class BookListView(ListView):
    model = BookModel
    template_name = 'bookms/book_list.html'  
    context_object_name = 'book_table'  

    def get_queryset(self):
        return BookModel.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book_table'] = BookTable(self.get_queryset())
        return context


class BookUpdateView(UpdateView):
    model= BookModel
    form_class=BookForm
    template_name='bookms/update_book.html'
    success_url = reverse_lazy('bookms:book_list')

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['book'] = self.get_object()
        return context

class BookDeleteView(DeleteView):
    model = BookModel
    template_name = 'bookms/delete_book.html'
    success_url = reverse_lazy('bookms:book_list')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = self.get_object()
        return context
    


class BorrowBookView(CreateView):
    model = Borrow
    form_class = BorrowForm 
    template_name = 'bookms/borrow_book.html'

    def get_initial(self):
        initial = super().get_initial()
        book_id = self.kwargs.get('book_id')
        initial['book'] = get_object_or_404(BookModel, id=book_id)
        return initial
         
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book_id = self.kwargs.get('book_id')
        context['book'] = get_object_or_404(BookModel, id=book_id)
        return context
    
    def get_success_url(self):
        instance = self.object
        return reverse_lazy('bookms:borrow_confirm',kwargs={'borrow_id':instance.id})
    

class ConfirmBookView(CreateView):
    model=Borrow
    form_class = BorrowForm 
    template_name= 'bookms/borrow_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        borrow_id = self.kwargs.get('borrow_id')
        context['borrow_entry'] = get_object_or_404(Borrow, id=borrow_id)
        return context
    

class BorrowedBooksListView(TemplateView):
    template_name = 'bookms/borrowed_books_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.filter(borrow__isnull=False).distinct()
        user_id = self.request.GET.get('user_id')
        
        if user_id:
            selected_user = get_object_or_404(User, id=user_id)
            context['selected_user'] = selected_user
            context['borrowed_books'] = Borrow.objects.filter(borrowed_by=selected_user)
        else:
            context['borrowed_books'] = None

        return context
    

class ReturnBookView(TemplateView):
    template_name ='bookms/return_book_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    
class ReturnBookDetailView(DetailView):
    model = Borrow
    template_name = 'bookms/return_book_detail.html'
    context_object_name = 'borrow_entry'
    pk_url_kwarg = 'borrow_id'


class MarkBookStatusView(UpdateView):
    model = BookModel
    template_name = 'bookms/return_book_detail.html'
    context_object_name = 'borrow_entry'
    form_class = BookStatusForm

    def get_success_url(self):
        
        return reverse('bookms:remove_book')  

    def form_valid(self, form):
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context
   
class RemoveBookView(DeleteView):
    model = BookModel
    template_name = 'bookms/remove_book_confirm.html'
    success_url = reverse_lazy('bookms:book_list')

    def get_object(self, queryset=None):
        return get_object_or_404(BookModel, id=self.kwargs['book_id'])
    

class RemoveBookConfirmationView(DeleteView):
    model = BookModel  
    template_name = 'bookms/remove_book_confirm.html' 
    success_url = reverse_lazy('bookms:book_list')

    def get_object(self, queryset=None):
        """Override to get the book object to be deleted."""
        return get_object_or_404(BookModel, id=self.kwargs['book_id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = self.get_object() 
        return context
    

bookms/templates/bookms/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django Project{% endblock %}</title>
    
    <!-- Bootstrap CSS CDN -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    {%include 'bookms\navbar.html'%}
    
    {% block content %}
    {% endblock content %}

    
</body>
</html>

bookms/templates/bookms/book_detail.html
{% extends 'bookms/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Borrow Books{% endblock %}

<h1>{{ book_copy.book.name }}</h1>
<p>Author: {{ book_copy.book.author }}</p>
<p>Status: {{ book_copy.status }}</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Borrow this book</button>
</form>

{% if messages %}
    {% for message in messages %}
        <div class="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
    
{% endblock %}

bookms/templates/bookms/book_list.html
{% extends 'bookms/base.html' %}
{% load django_tables2 %} 

{% block title %}Book List{% endblock %}

{% block content %}
<h1>List of Books</h1>
{% if book_table %}
    {% render_table book_table %}
{% else %}
    <p>No books available.</p>

    
{% endif %}
<a href="{% url 'bookms:book-create' %}" class="btn btn-primary">Add New Book</a>
{% endblock %}

bookms/templates/bookms/book_view.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>List of Book</title>
        
    </head>
    <body>
        {% render_table object_list %}
    </body>
</html>

bookms/templates/bookms/bookmodel_form.html
{% extends 'bookms/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Create Book{% endblock %}

{% block content %}
    <h1>Create Book</h1>
    <form method="post" action="{% url 'bookms:book-create' %}">
        {% csrf_token %}
        {{ form|crispy }}  
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{% url 'bookms:book_list' %}" class="btn btn-secondary ">Back to Book List</a>
    </form>
    
{% endblock %}

bookms/templates/bookms/borrow_book.html
{% extends 'bookms/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Borrow Book{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mb-4">Borrow Book: {{ book.name }}</h2>

    <div class="card mb-4">
        <div class="card-body">
            <p><strong>Author:</strong> {{ book.author }}</p>
            <p><strong>Price:</strong> ${{ book.price }}</p>
            <p><strong>Version:</strong> {{ book.version }}</p>
            <p><strong>Publication Info:</strong> {{ book.publication_info }}</p>
            <p><strong>ISBN:</strong> {{ book.isbn }}</p>
        </div>
    </div>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  
    
        <button type="submit" class="btn btn-success">Confirm Borrow</button>
    </form>
</div>


{% endblock %}

bookms/templates/bookms/borrow_details.html
{% extends 'bookms/base.html' %}
{% block title %}Borrow Confirmation{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mb-4">Borrow Confirmation</h2>

    <div class="card mb-4">
        <div class="card-body">
            <p><strong>Book Name:</strong> {{ borrow_entry.book.name }}</p>
            <p><strong>Author:</strong> {{ borrow_entry.book.author }}</p>
            <p><strong>Borrowed By:</strong> {{ borrow_entry.user.username }}</p>
            <p><strong>Borrowed Date:</strong> {{ borrow_entry.borrowed_at|date:"Y-m-d" }}</p>
           
        </div>
    </div>

    <a href="{% url 'bookms:book_list' %}" class="btn btn-primary">Back to Book List</a>
</div>
{% endblock %}

bookms/templates/bookms/borrowed_books_list.html
{% extends 'bookms/base.html' %}
{% block title %}Borrowed Books List{% endblock %}

{% block content %}
<div class="container">
    <h2>Borrowed Books</h2>
    {% if borrowed_books %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Book Name</th>
                <th>Borrowed By</th>
                <th>Borrowed On</th>
                <th>Return Date</th>  
                <th>Status</th>
                <th>Action</th>  
            </tr>
        </thead>
        <tbody>
            {% for borrow in borrowed_books %}
            <tr>
                <td>{{ borrow.book.name }}</td>
                <td>{{ borrow.borrowed_by.username }}</td>
                <td>{{ borrow.borrowed_at|date:"Y-m-d H:i:s" }}</td>
                <td>
                    {% if borrow.returned %}
                        {{ borrow.returned_at|date:"Y-m-d H:i:s" }} 
                    {% else %}
                        <span class="text-muted">Not Returned</span>  
                    {% endif %}
                </td>
                <td>
                    {% if borrow.returned %}
                        <span class="badge bg-success">Returned</span>
                    {% else %}
                        <span class="badge bg-warning">Not Returned</span>
                    {% endif %}
                </td>
                <td>
                    {% if not borrow.returned %}
                        <a href="{% url 'bookms:return_book_detail' borrow.id %}" class="btn btn-primary">Return Book</a>
                    {% else %}
                        <span class="text-muted">Already Returned</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No borrowed books available.</p>
    {% endif %}
</div>
{% endblock %}

bookms/templates/bookms/delete_book.html
{% extends 'bookms/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Delete Book{% endblock %}

{% block content %}
<h1>Are you sure you want to delete.... "{{ book.name }}"?</h1>
    <form method="post" action="{% url 'bookms:book_delete' book.pk %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Delete</button>
        <a href="{% url 'bookms:book_list' %}" class="btn btn-secondary">Cancel</a>  
    </form>
{% endblock %}

bookms/templates/bookms/navbar.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container-fluid">
        
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bookms:book-create' %}">Add Book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bookms:book_list' %}">Book list</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bookms:borrowed_books_list' %}">return book</a>
                </li>
                
            </ul>
        </div>
    </div>
</nav>

bookms/templates/bookms/remove_book_confirm.html
{% extends 'bookms/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Delete Book{% endblock %}

{% block content %}
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Remove Book
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Confirm Delition</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form id="deleteBookForm" method="POST" action="{% url 'bookms:remove_book' book.id %}"></form>
          <button type="button" class="btn btn-primary">Delete</button>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

bookms/templates/bookms/return_book_detail.html
{% extends 'bookms/base.html' %}
{% block title %}Return Book Details{% endblock %}

{% block content %}
<div class="container">
    <h2>Return Book Details</h2>

    <div class="card">
        <div class="card-body">
            <p><strong>Book Name:</strong> {{ borrow_entry.book.name }}</p>
            <p><strong>Author:</strong> {{ borrow_entry.book.author }}</p>
            <p><strong>Borrowed By:</strong> {{ borrow_entry.borrowed_by.username }}</p>
            <p><strong>Borrowed Date:</strong> {{ borrow_entry.borrowed_at|date:"Y-m-d" }}</p>
            <p><strong>Return Date:</strong> {{ borrow_entry.returned_at|date:"Y-m-d" }}</p>

        </div>
    </div>

    
{% endblock %}

bookms/templates/bookms/update_book.html
{% extends 'bookms/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update Book{% endblock %}

{% block content %}
    <h1>Update Book</h1>
    <form method="post" action="{% url 'bookms:book_update' book.pk %}">
        {% csrf_token %}
        {{ form|crispy }}  
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}